# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - eloebiznes-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5fe8c9b6178d4dbe9cd408a40ec9cf26 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f91978c4f7084747b2d2e41dec5816e0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fe8c9b6178d4dbe9cd408a40ec9cf26 }}/kris454/ebiznes2021-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eloebiznes-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87aa10908a874c75aaabdb7d5a06e132 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5fe8c9b6178d4dbe9cd408a40ec9cf26 }}/kris454/ebiznes2021-frontend:${{ github.sha }}'